# Generated by Django 4.1.7 on 2023-04-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rang_pasteur_rang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bureau',
            name='nomPrenom',
        ),
        migrations.AddField(
            model_name='bureau',
            name='pasteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.pasteur'),
        ),
    ]
