# Generated by Django 4.1.7 on 2023-04-11 02:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_bureau_nomprenom_bureau_pasteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
