# Generated by Django 4.1.7 on 2023-04-11 02:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
